const prefix = `ProductContext`;

export const PRODUCT_LIST_REQUEST = `${prefix}PRODUCT_LIST_REQUEST`;
export const PRODUCT_LIST_SUCCESS = `${prefix}PRODUCT_LIST_SUCCESS`;
export const PRODUCT_LIST_FAIL = `${prefix}PRODUCT_LIST_FAIL`;

export const PRODUCT_DETAILS_REQUEST = `${prefix}PRODUCT_DETAILS_REQUEST`;
export const PRODUCT_DETAILS_SUCCESS = `${prefix}PRODUCT_DETAILS_SUCCESS`;
export const PRODUCT_DETAILS_FAIL = `${prefix}PRODUCT_DETAILS_FAIL`;

export const PRODUCT_CREATE_REVIEW_REQUEST = `${prefix}PRODUCT_CREATE_REVIEW_REQUEST`;
export const PRODUCT_CREATE_REVIEW_SUCCESS = `${prefix}PRODUCT_CREATE_REVIEW_SUCCESS`;
export const PRODUCT_CREATE_REVIEW_FAIL = `${prefix}PRODUCT_CREATE_REVIEW_FAIL`;
export const PRODUCT_CREATE_REVIEW_RESET = `${prefix}PRODUCT_CREATE_REVIEW_RESET`;